# .planemo.yml
galaxy_tool_dir: tools
test_data_dir: test-data

# Namespace for mulled container builds
mulled_namespace: galaxytrakr

# Skip auxiliary XMLs that aren't standalone tools
shed_upload_blacklist:
  - macros.xml
  - test-data
  - data_manager_conf.xml
  - tool_data_table_conf.xml
  - tool_data_table_conf.xml.sample
