name: lissero
owner: estrain
description: In silico serogroup typing prediction for Listeria monocytogenes
long_description: |-
  Serogroup predictions from genome assemblies for Listeria monocytogenes
homepage_url: https://github.com/MDU-PHL/lissero
type: unrestricted
categories: []
