name: gtdbtk_classify_wf
owner: estrain
description: GTDB-Tk Classify genomes tool from the gtdbtk suite
long_description: |-
  GTDB-Tk is a software tool kit for assigning objective taxonomic classifications
  to bacterial and archaeal genomes based on the Genome Database Taxonomy GTDB. It
  is designed to work with recent advances that allow hundreds or thousands of
  metagenome-assembled genomes (MAGs) to be obtained directly from environmental
  samples. It can also be applied to isolate and single-cell genomes.
homepage_url: https://github.com/Ecogenomics/GTDBTk
type: unrestricted
categories: []
