name: Biocontainer-Style Planemo Build

on:
  push:
    branches: [ main ]
    paths:
      - 'tools/**/*.xml'
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Containers
    runs-on: ubuntu-latest

    steps:
      # --- Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Install Docker and dependencies (already present on GH runners)
      - name: Verify Docker
        run: docker --version

      # --- Setup Python and Planemo (no micromamba)
      - name: Install Planemo
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install planemo edam-ontology

      # --- Log in to Quay.io (like Biocontainers automation)
      - name: Authenticate to Quay.io
        env:
          QUAY_USER: ${{ secrets.QUAY_USER }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        run: |
          echo "$QUAY_PASSWORD" | docker login quay.io -u "$QUAY_USER" --password-stdin
          echo "Logged into quay.io as $QUAY_USER"

      # --- Pre-pull Miniforge and base images
      - name: Pull Base Images
        run: |
          docker pull quay.io/condaforge/miniforge3:latest
          docker pull quay.io/bioconda/base-glibc-busybox-bash:latest

      # --- Build loop: equivalent to Biocontainers' involucro invocation
      - name: Build and Push Containers
        env:
          QUAY_USER: ${{ secrets.QUAY_USER }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        run: |
          set -e

          TOOL_XMLS=$(find tools -type f -name "*.xml" ! -name "macros*.xml" ! -path "*/test-data/*")
          echo "Discovered tool XMLs:"
          echo "$TOOL_XMLS"

          for xml in $TOOL_XMLS; do
            echo "------------------------------------------"
            echo "Building Biocontainer-style image for $xml"
            echo "------------------------------------------"

            # Run Planemo Mull (same as Biocontainers' involucro + conda)
            planemo mull \
              --mulled_namespace galaxytrakr \
              "$xml" || { echo "Build failed for $xml"; continue; }

            # Load built image
            #TAR_PATH=$(find ~/.planemo/involucro/dist -type f -name "*.tar" | tail -n 1 || true)
            #if [ ! -f "$TAR_PATH" ]; then
            #  echo "No image tarball for $xml"
            #  continue
            #fi

            #docker load < "$TAR_PATH"

            IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep "galaxytrakr" | head -n 1 || true)
            if [ -z "$IMAGE" ]; then
              echo "No built image found for $xml"
              continue
            fi

            # Push to Quay.io (like Biocontainers automation)
            echo "Pushing image: $IMAGE"
            docker push "$IMAGE" || echo "Push failed for $IMAGE"
          done

