name: Planemo CI

on:
  push:
    branches: [ main ]
    paths:
      - 'tools/**/*.xml'
      - 'environment.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  planemo:
    name: Lint, Test, and Build Containers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment: false
          cache-downloads: false
          init-shell: bash

      - name: Install edam-ontology
        shell: bash -l {0}
        run: |
          set -e
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate planemo-env
          python -m pip install --no-cache-dir --upgrade edam-ontology
          python -c "import edam_ontology; print('edam_ontology import successful')"

      - name: Lint all tools
        shell: bash -l {0}
        run: |
          set -e
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate planemo-env
          planemo lint --recursive tools/

      - name: Test tools
        shell: bash -l {0}
        run: |
          set -e
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate planemo-env
          planemo test --recursive tools/ || echo "Some tests failed or have no test-data."

      - name: Log in to Quay.io
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        run: |
          echo "$QUAY_PASSWORD" | docker login quay.io -u "$QUAY_USERNAME" --password-stdin

      - name: Build and push containers
        shell: bash -l {0}
        run: |
          set -e
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate planemo-env

          TOOL_XMLS=$(find tools -mindepth 2 -maxdepth 4 -type f -name "*.xml" \
            ! -name "macros*.xml" \
            ! -name "data_manager_conf.xml" \
            ! -path "*/test-data/*")

          echo "Discovered tool XMLs:"
          echo "$TOOL_XMLS"

          for xml in $TOOL_XMLS; do
            echo "----------------------------------------"
            echo "Building and pushing container for: $xml"
            echo "----------------------------------------"

            planemo mull \
              --mulled_namespace galaxytrakr \
              --namespace quay.io/galaxytrakr \
              "$xml" || echo "Skipped $xml (Planemo mull failed)"
          done

      - name: Summary
        shell: bash -l {0}
        run: |
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate planemo-env
          planemo --version
          echo "Planemo CI complete"

