name: Sync Galaxy Tools to Tool Shed via Planemo

on:
  push:
    branches: [main]
    paths:
      - 'tools/**'
  pull_request:
    branches: [main]
    paths:
      - 'tools/**'
  workflow_dispatch:

jobs:
  sync-tools:
    name: Upload Changed Tools to Tool Shed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install Planemo and dependencies
        run: |
          set -euo pipefail
          sudo apt-get update -qq
          sudo apt-get install -y python3 python3-venv python3-pip curl rsync
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install planemo

      - name: Identify Changed Tool Directories
        id: changes
        run: |
          set -euo pipefail
          echo "Detecting changed Galaxy tools..."
          CHANGED=$(git diff --name-only HEAD^ HEAD | grep '^tools/' || true)

          # Extract only top-level tool directories directly under tools/
          echo "$CHANGED" | sed -E 's|^tools/([^/]+).*|tools/\1|' | sort -u > changed_dirs.txt

          if [[ -s changed_dirs.txt ]]; then
            echo "Detected changed tool directories:"
            cat changed_dirs.txt
            echo "tool_dirs=$(paste -sd ' ' changed_dirs.txt)" >> "$GITHUB_OUTPUT"
          else
            echo "No changed tools detected."
            echo "tool_dirs=" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload to Tool Shed
        if: steps.changes.outputs.tool_dirs != ''
        env:
          PLANEMO_SHED_KEY: ${{ secrets.TOOL_SHED_KEY }}
          PLANEMO_SHED_TARGET: opentrakr
          PLANEMO_OPENTRAKR_URL: https://opentrakr.org
          HG_USER: ${{ secrets.HG_USER }}
        run: |
          set -euo pipefail
          source .venv/bin/activate

          if [[ -z "$PLANEMO_SHED_KEY" ]]; then
            echo "Error: TOOL_SHED_KEY not set."
            exit 1
          fi

          if [[ -z "$HG_USER" ]]; then
            echo "Error: HG_USER not set."
            exit 1
          fi

          for dir in ${{ steps.changes.outputs.tool_dirs }}; do
            TOOL_NAME=$(basename "$dir")
            echo ">>> Uploading ${TOOL_NAME} to Tool Shed at ${PLANEMO_OPENTRAKR_URL}..."
            echo "    Owner: ${HG_USER}"

            # Try both the parent and inner directory for the tool
            CANDIDATES=("$dir" "$dir/$TOOL_NAME")
            TARGET_DIR=""

            for candidate in "${CANDIDATES[@]}"; do
              if find "$candidate" -maxdepth 1 -type f -name "*.xml" \
                  | xargs grep -E -q "<(tool|data_manager)"; then
                TARGET_DIR="$candidate"
                break
              fi
            done

            if [[ -z "$TARGET_DIR" ]]; then
              echo "   Skipping ${TOOL_NAME} — no Galaxy tool or data_manager XML found."
              continue
            fi

            echo "   Found Galaxy tool definitions in ${TARGET_DIR}"
            planemo shed_upload \
              --shed_target "$PLANEMO_SHED_TARGET" \
              --force_repository_creation \
              --tar_only \
              --owner "$HG_USER" \
              "$TARGET_DIR"

            echo "   [${TOOL_NAME}] upload complete."
          done

          echo "All changed tools uploaded successfully via Planemo."
